server:
  port: 8080

spring:
  application:
    name: nfy-example
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          name: nfy
          url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.dynamic.datasource.master.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        slave:
          name: nfy
          url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.dynamic.datasource.slave.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


knife4j:
  enable: true
  openapi:
    title: 业务系统接口文档
    description: "xxx 系统接口接口文档描述"
    email: lizhiup@gmail.com
    concat: nfy
    version: v4.0
    group:
      key1:
        group-name: Root接口
        api-rule: package
        api-rule-resources:
          - com.nfy.controller
      key2:
        group-name: 系统接口
        api-rule: package
        api-rule-resources:
          - com.nfy.module.system





